### ISSUE TITLE
error in pm10 and pm25 concentration

### ISSUE THREAD

**Issue by bensijtsma** [NodeJournalism/DustDuino#2]
Hi Matt,

It took me a while to find the error between my own calculations and the arduino ones in your program. It turns out that lines 115 and 123 contain a mistake. You write (4/3)*pi etc. It so happens that Arduino interprets (4/3) as an integer division and its result is 1. If you make it (4.0/3.0) it is a float calculation and the result is 1.333333. Thus your concentrations are off by 33%. 

Could you please correct?

Kind regards, Ben

**Comment by MattSchroyer** [comment]
Hi Ben,

Thank you for alerting me to this issue. I've changed the calculations in both the serial and regular versions of the sketch.

**Comment by bensijtsma** [comment]
Hi Matt,

Many thanks for those corrections.

I’m struggling a bit with the conversion of particle count to mass concentration.

My numbers are way too high and I live in a clean environment. Sometimes the calculated mass  concentration via your formula’s get me over 40 times the maximum norm in The Netherlands.

I guess I’m doing something wrong with the units or so.

Do you still have access to http://wireless.ece.drexel.edu/research/sd_air_quality.pdf 

You quote it and I’m not able to find it, link is broken, nor does googling sd_air_quality.pdf yield anything

Kind regards, Ben
